window.tyrano_lang = {
    word: {
        go_title: "Вернуться на титульный экран?",
        exit_game: "Закрыть окно и выйти из игры?",
        not_saved: "Сохранённых данных пока нет.",
        confirm: "Подтверждение",
        confirm_beforeunload: "Есть несохранённые данные. Выйти из игры?",
        tag: "Тег",
        not_exists: "не существует.",
        error: "Произошла ошибка. Проверьте сценарий.",
        label: "Метка",
        label_double: "дублируется в одном файле сценария.",
        error_occurred: "Произошла ошибка.",
        save_file_violation_1: "Обнаружено перемещение файла сохранения. Не загружайте его, если не уверены, что он заслуживает доверия.",
        save_file_violation_2: "Загрузить сохранение и запустить игру?",
        save_file_violation_3: "Запуск отменён. Удалите файл сохранения и запустите игру снова.",
        double_start: "Игра уже запущена. Запустить её повторно нельзя.",
        reload: "Перезагрузить",
        line: "строка { line }",
        initialized_saved_data: "Данные сохранений инициализированы.",
        initializing_saved_data: "Инициализировать данные сохранений?",
        saved_data_is_corrupted: "Сохранение может быть повреждено. Инициализировать данные сохранений?",
        save_does_not_work: "В этой среде функция сохранения не работает. Такое бывает, например, при локальном запуске.",
        undefined_tag: "Тег «{ name }» не существует.",
        undefined_label: "Метка «{ name }» не существует.",
        undefined_character: "Указанный персонаж «{ name }» не определён. Определите его с помощью [chara_new].",
        undefined_face: "Выражение лица «{ face }» указанного персонажа «{ name }» не определено. Определите его с помощью [chara_face].",
        undefined_character_parts: "Дополнительные части указанного персонажа «{ name }» не определены. Определите их с помощью [chara_layer].",
        undefined_keyframe: "Указанная анимация ключевых кадров «{ keyframe }» не определена. Определите её с помощью [keyframe].",
        undefined_3d_model: "Указанная 3D-модель «{ name }» не определена.",
        preload_failure_sound:
            "Звуковой файл «{ src }» не найден. Указан ли полный путь?\n\n(Правильный пример) ./data/bgm/my_bgm.mp3",
        preload_failure_image:
            "Файл изображения «{ src }» не найден. Указан ли полный путь?\n\n(Правильный пример) ./data/image/my_image.png",
        preload_failure_video:
            "Видеофайл «{ src }» не найден. Указан ли полный путь?\n\n(Правильный пример) ./data/video/my_video.mp4",
        invalid_keyframe: "Недопустимое значение ключевого кадра.",
        invalid_keyframe_percentage:
            'Процентное значение «{ percentage }», заданное для ключевого кадра, недопустимо. Укажите его, например, как "0%" или "30%".',
        error_in_iscript: "Внутри [iscript] произошла ошибка.",
        missing_endif: "После [if] не найден ни один из тегов [elsif], [else] или [endif]. Либо внутри [if] слишком много тегов.",
        missing_endmacro: "После [macro] не найден [endmacro]. Либо внутри [macro] слишком много тегов.",
        missing_endignore: "После [ignore] не найден [endignore]. Либо внутри [ignore] слишком много тегов.",
        missing_parameter: "Для тега «{ tag }» обязателен параметр «{ param }».",
        if_and_endif_do_not_match: "Количество [if] и [endif] не совпадает.",
        unsupported_extensions: "«{ ext }» — неподдерживаемый формат файла.",
        undefined_keyconfig:
            'Конфигурация клавиш не определена. Возможно, файл KeyConfig.js отсутствует или содержит синтаксическую ошибку. Проверьте, не пропущены ли запятые "," или скобки "]" и "}".',
        compensate_missing_quart:
            'Обнаружена неожиданная "]". Возможно, в параметрах не хватает кавычек, поэтому скрипт будет автоматически исправлен и интерпретирован.\n\nДо исправления: { before }\nПосле исправления: { after }',
        duplicate_label:
            "Метка «{ name }» дублируется в одном файле сценария. Не используйте одинаковые имена меток в одном файле сценария.",
        file_not_found: "Файл не найден.\n\n{ path }",
        patch_not_found: "Файл патча не найден.\n\n{ path }",
        new_patch_found: "Найдено новое обновление.\n\nВерсия: { version }\n{ message }\n\nУстановить обновление?",
        apply_web_patch: "Устанавливается обновление. После завершения игра завершится автоматически.",
        apply_patch_complete: "Обновление установлено. Перезапустите игру.",
    },

    novel: {
        file_menu_button_save: "menu_button_save.gif",
        file_menu_button_load: "menu_button_load.gif",
        file_menu_button_message_close: "menu_message_close.gif",
        file_menu_button_skip: "menu_button_skip.gif",
        file_menu_button_title: "menu_button_title.gif",
        file_menu_button_close: "menu_button_close.png",
        file_menu_bg: "menu_bg.jpg",
        file_save_bg: "menu_save_bg.jpg",
        file_load_bg: "menu_load_bg.jpg",
        file_button_menu: "button_menu.png",
    },
};
