window.tyrano_lang = {
    word: {
        go_title: "Return to the title screen?",
        exit_game: "Close the window and exit the game?",
        not_saved: "There is no saved data yet.",
        confirm: "Confirm",
        confirm_beforeunload: "There is unsaved data. Exit the game?",
        tag: "Tag",
        not_exists: " does not exist.",
        error: "An error occurred. Please check the script.",
        label: "Label",
        label_double: " is duplicated in the same scenario file.",
        error_occurred: "An error occurred.",
        save_file_violation_1: "The save data appears to have been moved. Never load it unless you know it is trustworthy.",
        save_file_violation_2: "Load this save data and start the game?",
        save_file_violation_3: "Launch canceled. Delete the save data and start the game again.",
        double_start: "The game is already running. It cannot be launched twice.",
        reload: "Reload",
        line: "line { line }",
        initialized_saved_data: "Save data has been initialized.",
        initializing_saved_data: "Initialize the save data?",
        saved_data_is_corrupted: "The save data may be corrupted. Initialize the save data?",
        save_does_not_work: "Saving does not work in this environment. This can happen, for example, when running locally.",
        undefined_tag: "Tag \"{ name }\" does not exist.",
        undefined_label: "Label \"{ name }\" does not exist.",
        undefined_character: "The specified character \"{ name }\" has not been defined. Define it with [chara_new].",
        undefined_face: "The expression \"{ face }\" for the specified character \"{ name }\" has not been defined. Define it with [chara_face].",
        undefined_character_parts: "The additional parts for the specified character \"{ name }\" have not been defined. Define them with [chara_layer].",
        undefined_keyframe: "The specified keyframe animation \"{ keyframe }\" has not been defined. Define it with [keyframe].",
        undefined_3d_model: "The specified 3D model \"{ name }\" has not been defined.",
        preload_failure_sound:
            "Audio file \"{ src }\" was not found. Was the full path specified?\n\n(Example) ./data/bgm/my_bgm.mp3",
        preload_failure_image:
            "Image file \"{ src }\" was not found. Was the full path specified?\n\n(Example) ./data/image/my_image.png",
        preload_failure_video:
            "Video file \"{ src }\" was not found. Was the full path specified?\n\n(Example) ./data/video/my_video.mp4",
        invalid_keyframe: "The keyframe value is invalid.",
        invalid_keyframe_percentage:
            'The percentage "{ percentage }" set for the keyframe is invalid. Specify it as, for example, "0%" or "30%".',
        error_in_iscript: "An error occurred inside [iscript].",
        missing_endif: "None of [elsif], [else], or [endif] was found after [if]. Alternatively, there are too many tags inside [if].",
        missing_endmacro: "[endmacro] was not found after [macro]. Alternatively, there are too many tags inside [macro].",
        missing_endignore: "[endignore] was not found after [ignore]. Alternatively, there are too many tags inside [ignore].",
        missing_parameter: "The parameter \"{ param }\" is required for the tag \"{ tag }\".",
        if_and_endif_do_not_match: "The number of [if] and [endif] tags does not match.",
        unsupported_extensions: "\"{ ext }\" is an unsupported file format.",
        undefined_keyconfig:
            'Key configuration is not defined. KeyConfig.js may be missing or contain a syntax error. Check that commas "," or brackets "]" and "}" have not been omitted.',
        compensate_missing_quart:
            'An unexpected "]" was detected. There may not be enough quotes in the parameters, so the script will be corrected and interpreted automatically.\n\nBefore correction: { before }\nAfter correction: { after }',
        duplicate_label:
            "Label \"{ name }\" is duplicated in the same scenario file. Do not use the same label name more than once in a scenario file.",
        file_not_found: "File not found.\n\n{ path }",
        patch_not_found: "Patch file not found.\n\n{ path }",
        new_patch_found: "A new update is available.\n\nVersion: { version }\n{ message }\n\nWould you like to install the update?",
        apply_web_patch: "The update will now be installed. The game will close automatically when it is complete.",
        apply_patch_complete: "The update has been installed. Please restart the game.",
    },

    novel: {
        file_menu_button_save: "menu_button_save.gif",
        file_menu_button_load: "menu_button_load.gif",
        file_menu_button_message_close: "menu_message_close.gif",
        file_menu_button_skip: "menu_button_skip.gif",
        file_menu_button_title: "menu_button_title.gif",
        file_menu_button_close: "menu_button_close.png",
        file_menu_bg: "menu_bg.jpg",
        file_save_bg: "menu_save_bg.jpg",
        file_load_bg: "menu_load_bg.jpg",
        file_button_menu: "button_menu.png",
    },
};
